import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNavbar from "@/components/BottomNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pet Reminder App",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["nextjs", "next14", "pwa", "next-pwa"],
  themeColor: [{media: "(prefers-color-scheme: dark)", color: "#fff"}],
  authors: [{
    name: "Roshan Sharma",
    url: "https://roshan-sharma-portfolio.vercel.app/"
  }],
  viewport: "minimum-scale=1, intial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover",
  icons: {
    icon: [
      { url: "/../../public/icons/next-pwa-logo-192.png", sizes: "192x192", type: "image/png" },
      { url: "/../../public/icons/icons512_maskable.png", sizes: "512x512", type: "image/png" },
    ],
    apple: "/../../public/icons/icons512_maskable.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#ffffff" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="icons512_maskable.png" />
        <link rel="icon" href="icons512_rounded.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <BottomNavbar />
      </body>
    </html>
  );
}


